# Generated by Django 4.2.16 on 2024-09-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_points_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'verbose_name': 'Point', 'verbose_name_plural': 'Points'},
        ),
    ]
