# Generated by Django 4.2.16 on 2024-09-06 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_store_purchases_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
