# Generated by Django 4.2.16 on 2024-09-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_address_remove_customer_cnpj_and_more'),
        ('purchases', '0004_purchases_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchases',
            options={'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='user',
        ),
        migrations.AddField(
            model_name='purchases',
            name='invoice',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
