# Generated by Django 4.2.16 on 2024-09-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchases_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='Events',
            new_name='event',
        ),
    ]
