# Generated by Django 4.2.16 on 2024-09-20 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_alter_points_options'),
        ('customers', '0002_remove_customer_address_remove_customer_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='selected_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='points.store'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
