# Generated by Django 4.2.16 on 2024-09-20 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_alter_points_options'),
        ('customers', '0003_customer_selected_store_alter_customer_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='selected_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='points.store'),
        ),
    ]
